// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("HeiConv")>]
[<assembly: AssemblyProductAttribute("HeiConv")>]
[<assembly: AssemblyDescriptionAttribute("HEIC to JPG file converter. The goal for this application is simplicity over a lot of functionality.")>]
[<assembly: AssemblyVersionAttribute("0.2.2")>]
[<assembly: AssemblyFileVersionAttribute("0.2.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "HeiConv"
    let [<Literal>] AssemblyProduct = "HeiConv"
    let [<Literal>] AssemblyDescription = "HEIC to JPG file converter. The goal for this application is simplicity over a lot of functionality."
    let [<Literal>] AssemblyVersion = "0.2.2"
    let [<Literal>] AssemblyFileVersion = "0.2.2"
