# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- *

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core'
  inputs:
    packageType: sdk
    version: 3.0.100-preview7-012821
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: UseDotNet@2
  displayName: 'Install .NET Core 2.1'
  inputs:
    packageType: sdk
    version: 2.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- script: dotnet tool install fake-cli -g
  displayName: 'Install fake'
- script: fake build
  displayName: 'Execute build script'
